/* === Pandakreuzwort — Redaktionelle Wortbank (UMD) ===
   Ausschließlich selbst formulierte Hinweise und Antworten mit der
   Quelle project-editorial. Kein Fetch, keine externen Definitionen.
   gridAnswer wird zur Ladezeit via normalizeGridAnswer berechnet, um
   Transkriptionsfehler auszuschließen (NFC + klassische Umschrift
   Ä→AE, Ö→OE, Ü→UE und ß→SS).

   Bairische Einträge führen verpflichtend region und standardGerman
   (standarddeutsche Entsprechung/Bedeutung). */
(function (root, factory) {
    var logic = (typeof require === 'function')
        ? require('./pandakreuzwort-logic.js')
        : (root && root.PandakreuzwortLogic);
    var normalize = (logic && logic.normalizeGridAnswer)
        ? logic.normalizeGridAnswer
        : function (v) { return String(v || '').toUpperCase(); };

    var DATASET_VERSION = '2026-08-v1.5';

    // displayAnswer = natürliche Schreibweise; gridAnswer wird berechnet.
    var RAW = [
        // ============================================================
        // DEUTSCH (Standarddeutsch)
        // ============================================================
        { id: 'de-apfel', language: 'de', displayAnswer: 'Apfel', clue: 'Obst mit Kerngehäuse', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-tisch', language: 'de', displayAnswer: 'Tisch', clue: 'Möbel zum Abstellen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-stuhl', language: 'de', displayAnswer: 'Stuhl', clue: 'Sitzmöbel mit Lehne', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-haus', language: 'de', displayAnswer: 'Haus', clue: 'Gebäude zum Wohnen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-baum', language: 'de', displayAnswer: 'Baum', clue: 'Große Pflanze mit Stamm', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-blume', language: 'de', displayAnswer: 'Blume', clue: 'Pflanze mit bunten Blüten', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-sonne', language: 'de', displayAnswer: 'Sonne', clue: 'Gestirn am Tageshimmel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-mond', language: 'de', displayAnswer: 'Mond', clue: 'Erdtrabant in der Nacht', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-stern', language: 'de', displayAnswer: 'Stern', clue: 'Lichtpunkt am Nachthimmel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-wolke', language: 'de', displayAnswer: 'Wolke', clue: 'Wasserschleier am Himmel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-berg', language: 'de', displayAnswer: 'Berg', clue: 'Hohe Erhebung der Landschaft', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-fluss', language: 'de', displayAnswer: 'Fluss', clue: 'Fließendes Gewässer', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-insel', language: 'de', displayAnswer: 'Insel', clue: 'Landstück im Wasser', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-tuer', language: 'de', displayAnswer: 'Tür', clue: 'Durchgang zum Öffnen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-fenster', language: 'de', displayAnswer: 'Fenster', clue: 'Öffnung mit Glas', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-dach', language: 'de', displayAnswer: 'Dach', clue: 'Obere Abdeckung eines Hauses', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-zimmer', language: 'de', displayAnswer: 'Zimmer', clue: 'Bewohnbarer Raum', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-kueche', language: 'de', displayAnswer: 'Küche', clue: 'Raum zum Kochen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-bett', language: 'de', displayAnswer: 'Bett', clue: 'Möbel zum Schlafen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-uhr', language: 'de', displayAnswer: 'Uhr', clue: 'Gerät zur Zeitmessung', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-garten', language: 'de', displayAnswer: 'Garten', clue: 'Stück Land zum Pflanzen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-wald', language: 'de', displayAnswer: 'Wald', clue: 'Viele Bäume zusammen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-wiese', language: 'de', displayAnswer: 'Wiese', clue: 'Grüne Fläche mit Gras', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-rose', language: 'de', displayAnswer: 'Rose', clue: 'Blume mit Dornen am Stängel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-pilz', language: 'de', displayAnswer: 'Pilz', clue: 'Hutförmiger Waldbewohner', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-stein', language: 'de', displayAnswer: 'Stein', clue: 'Hartes einzelnes Stück aus natürlichem Mineralmaterial', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-feuer', language: 'de', displayAnswer: 'Feuer', clue: 'Brennende Flamme', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-wasser', language: 'de', displayAnswer: 'Wasser', clue: 'Flüssige chemische Verbindung H₂O', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-regen', language: 'de', displayAnswer: 'Regen', clue: 'Niederschlag aus Wassertropfen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-schnee', language: 'de', displayAnswer: 'Schnee', clue: 'Gefrorener Niederschlag in Flocken', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-wind', language: 'de', displayAnswer: 'Wind', clue: 'Bewegte Luft', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-eis', language: 'de', displayAnswer: 'Eis', clue: 'Gefrorenes Wasser', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-sturm', language: 'de', displayAnswer: 'Sturm', clue: 'Heftiger Wind', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-nebel', language: 'de', displayAnswer: 'Nebel', clue: 'Dichter Dunst über dem Land', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-himmel', language: 'de', displayAnswer: 'Himmel', clue: 'Blaue Wölbung über uns', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-erde', language: 'de', displayAnswer: 'Erde', clue: 'Planet, auf dem wir leben', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-komet', language: 'de', displayAnswer: 'Komet', clue: 'Schweifstern am Himmel', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-welt', language: 'de', displayAnswer: 'Welt', clue: 'Die ganze Erde', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-zeit', language: 'de', displayAnswer: 'Zeit', clue: 'Was die Uhr misst', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-jahr', language: 'de', displayAnswer: 'Jahr', clue: 'Zwölf Monate', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-monat', language: 'de', displayAnswer: 'Monat', clue: 'Etwa vier Wochen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-woche', language: 'de', displayAnswer: 'Woche', clue: 'Sieben Tage', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-nacht', language: 'de', displayAnswer: 'Nacht', clue: 'Zeit nach Sonnenuntergang', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-morgen', language: 'de', displayAnswer: 'Morgen', clue: 'Frühe Tageszeit', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-abend', language: 'de', displayAnswer: 'Abend', clue: 'Späte Tageszeit', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-stunde', language: 'de', displayAnswer: 'Stunde', clue: 'Sechzig Minuten', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-sekunde', language: 'de', displayAnswer: 'Sekunde', clue: 'Kurze Zeiteinheit', difficulty: 3, allowedProfiles: ['schwer'] },
        { id: 'de-fest', language: 'de', displayAnswer: 'Fest', clue: 'Fröhliche Feier', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-urlaub', language: 'de', displayAnswer: 'Urlaub', clue: 'Zeit der Erholung', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-reise', language: 'de', displayAnswer: 'Reise', clue: 'Fahrt in die Ferne', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-zug', language: 'de', displayAnswer: 'Zug', clue: 'Schienenfahrzeug', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-auto', language: 'de', displayAnswer: 'Auto', clue: 'Fahrzeug mit Motor', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-bus', language: 'de', displayAnswer: 'Bus', clue: 'Großes Fahrzeug für Viele', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-boot', language: 'de', displayAnswer: 'Boot', clue: 'Kleines Wasserfahrzeug', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-schiff', language: 'de', displayAnswer: 'Schiff', clue: 'Großes Wasserfahrzeug', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-rad', language: 'de', displayAnswer: 'Rad', clue: 'Rundes Rollteil', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-motor', language: 'de', displayAnswer: 'Motor', clue: 'Antrieb einer Maschine', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-lampe', language: 'de', displayAnswer: 'Lampe', clue: 'Lichtquelle im Raum', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-licht', language: 'de', displayAnswer: 'Licht', clue: 'Macht es hell', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-glas', language: 'de', displayAnswer: 'Glas', clue: 'Transparentes Material aus Quarzsand', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-holz', language: 'de', displayAnswer: 'Holz', clue: 'Material von Bäumen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-papier', language: 'de', displayAnswer: 'Papier', clue: 'Dünner Beschreibstoff', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-gold', language: 'de', displayAnswer: 'Gold', clue: 'Glänzendes Edelmetall', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-silber', language: 'de', displayAnswer: 'Silber', clue: 'Graues Edelmetall', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-messer', language: 'de', displayAnswer: 'Messer', clue: 'Schneidewerkzeug', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-gabel', language: 'de', displayAnswer: 'Gabel', clue: 'Essbesteck mit Zinken', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-loeffel', language: 'de', displayAnswer: 'Löffel', clue: 'Essbesteck zum Rühren', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-teller', language: 'de', displayAnswer: 'Teller', clue: 'Flaches Geschirr', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-tasse', language: 'de', displayAnswer: 'Tasse', clue: 'Henkelgefäß für Heißes', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-topf', language: 'de', displayAnswer: 'Topf', clue: 'Gefäß zum Kochen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-pfanne', language: 'de', displayAnswer: 'Pfanne', clue: 'Flaches Bratgeschirr', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-ofen', language: 'de', displayAnswer: 'Ofen', clue: 'Geschlossenes Gerät zum Backen oder Heizen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-hund', language: 'de', displayAnswer: 'Hund', clue: 'Treuer Vierbeiner', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-katze', language: 'de', displayAnswer: 'Katze', clue: 'Schnurrendes Haustier', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-maus', language: 'de', displayAnswer: 'Maus', clue: 'Kleines Nagetier', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-pferd', language: 'de', displayAnswer: 'Pferd', clue: 'Großes Reittier', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-kuh', language: 'de', displayAnswer: 'Kuh', clue: 'Milchgebendes Rind', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-gans', language: 'de', displayAnswer: 'Gans', clue: 'Vogel, der schnattert', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-fisch', language: 'de', displayAnswer: 'Fisch', clue: 'Wassertier mit Flossen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-vogel', language: 'de', displayAnswer: 'Vogel', clue: 'Tier mit Federn', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-biene', language: 'de', displayAnswer: 'Biene', clue: 'Honigsammelndes Insekt', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-ampel', language: 'de', displayAnswer: 'Ampel', clue: 'Verkehrslichtsignal', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-anker', language: 'de', displayAnswer: 'Anker', clue: 'Hält das Schiff fest', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-brief', language: 'de', displayAnswer: 'Brief', clue: 'Geschriebene Nachricht', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-buch', language: 'de', displayAnswer: 'Buch', clue: 'Gebundene Seiten zum Lesen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-seife', language: 'de', displayAnswer: 'Seife', clue: 'Zum Waschen der Hände', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-seil', language: 'de', displayAnswer: 'Seil', clue: 'Zum Binden und Klettern', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-nagel', language: 'de', displayAnswer: 'Nagel', clue: 'Kleines Befestigungsmittel aus Metall', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-hammer', language: 'de', displayAnswer: 'Hammer', clue: 'Werkzeug zum Schlagen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-zelt', language: 'de', displayAnswer: 'Zelt', clue: 'Behelfsunterkunft aus Stoff', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-mass', language: 'de', displayAnswer: 'Maß', clue: 'Bayerische Biermenge von einem Liter', difficulty: 3, allowedProfiles: ['schwer'] },
        { id: 'de-groesse', language: 'de', displayAnswer: 'Größe', clue: 'Ausdehnung eines Dings', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-strasse', language: 'de', displayAnswer: 'Straße', clue: 'Fahrbahn für Autos', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-fuss', language: 'de', displayAnswer: 'Fuß', clue: 'Körperteil zum Gehen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-nase', language: 'de', displayAnswer: 'Nase', clue: 'Gesichtsteil zum Riechen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-auge', language: 'de', displayAnswer: 'Auge', clue: 'Organ zum Sehen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-ohr', language: 'de', displayAnswer: 'Ohr', clue: 'Organ zum Hören', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-hand', language: 'de', displayAnswer: 'Hand', clue: 'Greifwerkzeug am Arm', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-arm', language: 'de', displayAnswer: 'Arm', clue: 'Glied zwischen Schulter und Hand', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-kopf', language: 'de', displayAnswer: 'Kopf', clue: 'Oberstes Körperteil', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-herz', language: 'de', displayAnswer: 'Herz', clue: 'Pumpendes Organ in der Brust', difficulty: 2, allowedProfiles: ['mittel', 'schwer'] },
        { id: 'de-blut', language: 'de', displayAnswer: 'Blut', clue: 'Rote Körperflüssigkeit', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-kuchen', language: 'de', displayAnswer: 'Kuchen', clue: 'Süßes Gebäck zum Kaffee', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-milch', language: 'de', displayAnswer: 'Milch', clue: 'Weiße Flüssigkeit der Kuh', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-brot', language: 'de', displayAnswer: 'Brot', clue: 'Gebackenes Grundnahrungsmittel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },
        { id: 'de-ei', language: 'de', displayAnswer: 'Ei', clue: 'Oval vom Huhn', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'] },

        // ============================================================
        // BAIRISCH — region und standardGerman verpflichtend.
        // ============================================================
        { id: 'bar-dahoam', language: 'bar', displayAnswer: 'Dahoam', clue: 'Bairisch für „zuhause"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'zuhause' },
        { id: 'bar-hendl', language: 'bar', displayAnswer: 'Hendl', clue: 'Bairisches grillfertiges Hähnchen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Brathähnchen' },
        { id: 'bar-brezn', language: 'bar', displayAnswer: 'Brezn', clue: 'Bairisch gebackene Teigbrezel', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Brezel' },
        { id: 'bar-radl', language: 'bar', displayAnswer: 'Radl', clue: 'Bairisch für Fahrrad', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Fahrrad' },
        { id: 'bar-bussi', language: 'bar', displayAnswer: 'Bussi', clue: 'Bairisches Küsschen auf die Wange', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Küsschen' },
        { id: 'bar-bam', language: 'bar', displayAnswer: 'Bam', clue: 'Bairisch für Baum', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Baum' },
        { id: 'bar-dirndl', language: 'bar', displayAnswer: 'Dirndl', clue: 'Bairisches Trachtenkleid mit Schürze', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Trachtenkleid' },
        { id: 'bar-watschn', language: 'bar', displayAnswer: 'Watschn', clue: 'Bairische Ohrfeige, die „Watsche"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Ohrfeige' },
        { id: 'bar-obazda', language: 'bar', displayAnswer: 'Obazda', clue: 'Bairischer Streich aus Camembert und Gewürzen', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Käsebrotaufstrich' },
        { id: 'bar-griassdi', language: 'bar', displayAnswer: 'Griaßdi', clue: 'Bairische Begrüßung: „Grüß dich"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Grüß dich' },
        { id: 'bar-zamm', language: 'bar', displayAnswer: 'Zamm', clue: 'Bairisch für „zusammen"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'zusammen' },
        { id: 'bar-madl', language: 'bar', displayAnswer: 'Madl', clue: 'Bairisch für Mädchen', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Mädchen' },
        { id: 'bar-bub', language: 'bar', displayAnswer: 'Bub', clue: 'Bairisch für Junge', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Junge' },
        { id: 'bar-schee', language: 'bar', displayAnswer: 'Schee', clue: 'Bairisch für „schön"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'schön' },
        { id: 'bar-ned', language: 'bar', displayAnswer: 'Ned', clue: 'Bairisch für „nicht"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'nicht' },
        { id: 'bar-boarisch', language: 'bar', displayAnswer: 'Boarisch', clue: 'Bairisch für „bairisch"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'bairisch' },
        { id: 'bar-gams', language: 'bar', displayAnswer: 'Gams', clue: 'Bairisch für das wendige Bergtier, die Gemse', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'alpin-bairisch', standardGerman: 'Gemse' },
        { id: 'bar-goass', language: 'bar', displayAnswer: 'Goass', clue: 'Bairisch für Ziege', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Ziege' },
        { id: 'bar-kas', language: 'bar', displayAnswer: 'Kas', clue: 'Bairisch für Käse', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Käse' },
        { id: 'bar-feia', language: 'bar', displayAnswer: 'Feia', clue: 'Bairisch für Feuer', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Feuer' },
        { id: 'bar-wiesn', language: 'bar', displayAnswer: 'Wiesn', clue: 'Bairisch für Wiese; auch Münchner Festwiese', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Wiese' },
        { id: 'bar-haxn', language: 'bar', displayAnswer: 'Haxn', clue: 'Bairisch für die gegarte Schweinshaxe', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Schweinshaxe' },
        { id: 'bar-mass', language: 'bar', displayAnswer: 'Maß', clue: 'Bairische Maßeinheit für einen Liter Bier', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Maßkrug (ein Liter)' },
        { id: 'bar-kraxn', language: 'bar', displayAnswer: 'Kraxn', clue: 'Bairischer Rückenkorb zum Tragen', difficulty: 3, allowedProfiles: ['schwer'], region: 'alpin-bairisch', standardGerman: 'Rückenkorb' },
        { id: 'bar-schaugn', language: 'bar', displayAnswer: 'Schaugn', clue: 'Bairisch für „schauen"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'schauen' },
        { id: 'bar-damisch', language: 'bar', displayAnswer: 'Damisch', clue: 'Bairisch für „verrückt, wild"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'verrückt' },
        { id: 'bar-brotzeit', language: 'bar', displayAnswer: 'Brotzeit', clue: 'Bairische kalte Mahlzeit mit Brot und Aufstrich', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Brotmahlzeit' },
        { id: 'bar-guglhupf', language: 'bar', displayAnswer: 'Guglhupf', clue: 'Bairischer Rührkuchen in Kranzform', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Gugelhupf' },
        { id: 'bar-fasching', language: 'bar', displayAnswer: 'Fasching', clue: 'Bairische Bezeichnung für Karneval', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Karneval' },
        { id: 'bar-pfanna', language: 'bar', displayAnswer: 'Pfanna', clue: 'Bairisch für Pfanne', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Pfanne' },
        { id: 'bar-suppa', language: 'bar', displayAnswer: 'Suppa', clue: 'Bairisch für Suppe', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Suppe' },
        { id: 'bar-kartoffl', language: 'bar', displayAnswer: 'Kartoffl', clue: 'Bairisch für Kartoffel', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Kartoffel' },
        { id: 'bar-oans', language: 'bar', displayAnswer: 'Oans', clue: 'Bairisch für die Zahl eins', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'eins' },
        { id: 'bar-zwoa', language: 'bar', displayAnswer: 'Zwoa', clue: 'Bairisch für die Zahl zwei', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'zwei' },
        { id: 'bar-drai', language: 'bar', displayAnswer: 'Drai', clue: 'Bairisch für die Zahl drei', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'drei' },
        { id: 'bar-fia', language: 'bar', displayAnswer: 'Fia', clue: 'Bairisch für die Zahl vier', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'vier' },
        { id: 'bar-fimfa', language: 'bar', displayAnswer: 'Fimfa', clue: 'Bairisch für die Zahl fünf', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'fünf' },
        { id: 'bar-wea', language: 'bar', displayAnswer: 'Wea', clue: 'Bairisch für das Fragewort „wer"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'wer' },
        { id: 'bar-wos', language: 'bar', displayAnswer: 'Wos', clue: 'Bairisch für das Fragewort „was"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'was' },
        { id: 'bar-wia', language: 'bar', displayAnswer: 'Wia', clue: 'Bairisch für das Fragewort „wie"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'wie' },
        { id: 'bar-do', language: 'bar', displayAnswer: 'Do', clue: 'Bairisch für „da, hier"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'da, hier' },
        { id: 'bar-liab', language: 'bar', displayAnswer: 'Liab', clue: 'Bairisch für „lieb, nett"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'lieb' },
        { id: 'bar-guad', language: 'bar', displayAnswer: 'Guad', clue: 'Bairisch für „gut"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'gut' },
        { id: 'bar-weng', language: 'bar', displayAnswer: 'Weng', clue: 'Bairisch für „ein wenig"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'ein wenig' },
        { id: 'bar-lumpa', language: 'bar', displayAnswer: 'Lumpa', clue: 'Bairisch für Lump oder alten Lappen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Lump, Lappen' },
        { id: 'bar-schneidig', language: 'bar', displayAnswer: 'Schneidig', clue: 'Bairisch für „flott, tüchtig"', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'flott, tüchtig' },
        { id: 'bar-nopf', language: 'bar', displayAnswer: 'Nopf', clue: 'Nordbairisches Wort für einen Kleidungsverschluss', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'nordbairisch', standardGerman: 'Knopf' },
        { id: 'bar-tropfa', language: 'bar', displayAnswer: 'Tropfa', clue: 'Bairisch für Tropfen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Tropfen' },
        { id: 'bar-fensta', language: 'bar', displayAnswer: 'Fensta', clue: 'Bairisch für Fenster', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Fenster' },
        { id: 'bar-soch', language: 'bar', displayAnswer: 'Soch', clue: 'Bairisch für „Sache, Ding"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Sache' },
        { id: 'bar-kircha', language: 'bar', displayAnswer: 'Kircha', clue: 'Bairisch für Kirche', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Kirche' },
        { id: 'bar-schuasta', language: 'bar', displayAnswer: 'Schuasta', clue: 'Bairisch für den Schuhmacher', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Schuster' },
        { id: 'bar-pfeffa', language: 'bar', displayAnswer: 'Pfeffa', clue: 'Bairisch für Pfeffer', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Pfeffer' },
        { id: 'bar-soiz', language: 'bar', displayAnswer: 'Soiz', clue: 'Alpin-bairisch für Salz', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'alpin-bairisch', standardGerman: 'Salz' },
        { id: 'bar-zucka', language: 'bar', displayAnswer: 'Zucka', clue: 'Bairisch für Zucker', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Zucker' },
        { id: 'bar-moehl', language: 'bar', displayAnswer: 'Möhl', clue: 'Bairisch für Mehl', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Mehl' },
        { id: 'bar-weckla', language: 'bar', displayAnswer: 'Weckla', clue: 'Fränkisch-bairisch für Brötchen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'fränkisch', standardGerman: 'Brötchen' },
        { id: 'bar-heferl', language: 'bar', displayAnswer: 'Heferl', clue: 'Bairisch-österreichisch für eine Tasse', difficulty: 3, allowedProfiles: ['schwer'], region: 'österreichisch-bairisch', standardGerman: 'Tasse' },
        { id: 'bar-schmarrn', language: 'bar', displayAnswer: 'Schmarrn', clue: 'Bairischer Pfannenkuchen; auch Unsinn', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Pfannengericht; Unsinn' },
        { id: 'bar-ross', language: 'bar', displayAnswer: 'Ross', clue: 'Bairisch für Pferd', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Pferd' },
        { id: 'bar-kua', language: 'bar', displayAnswer: 'Kua', clue: 'Bairisch für Kuh', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Kuh' },
        { id: 'bar-wassa', language: 'bar', displayAnswer: 'Wassa', clue: 'Bairisch für Wasser', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Wasser' },
        { id: 'bar-woid', language: 'bar', displayAnswer: 'Woid', clue: 'Bairisch für Wald', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Wald' },
        { id: 'bar-brod', language: 'bar', displayAnswer: 'Brod', clue: 'Bairisch für Brot', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Brot' },
        { id: 'bar-gell', language: 'bar', displayAnswer: 'Gell', clue: 'Bairische Bestätigung: „nicht wahr?"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'nicht wahr?' },
        { id: 'bar-jo', language: 'bar', displayAnswer: 'Jo', clue: 'Bairisch für „ja"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'ja' },
        { id: 'bar-na', language: 'bar', displayAnswer: 'Na', clue: 'Bairisch für „nein"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'nein' },
        { id: 'bar-lederhosn', language: 'bar', displayAnswer: 'Lederhosn', clue: 'Bairische knielange Lederhose', difficulty: 3, allowedProfiles: ['schwer'], region: 'alpin-bairisch', standardGerman: 'Lederhose' },
        { id: 'bar-servus', language: 'bar', displayAnswer: 'Servus', clue: 'Bairisch-österreichische Begrüßung und Verabschiedung', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'österreichisch-bairisch', standardGerman: 'Hallo; Tschüss' },
        { id: 'bar-grussgott', language: 'bar', displayAnswer: 'Grüß Gott', clue: 'Oberbairische Begrüßung', difficulty: 3, allowedProfiles: ['schwer'], region: 'oberbairisch', standardGerman: 'Grüß Gott' },
        { id: 'bar-fackl', language: 'bar', displayAnswer: 'Fackl', clue: 'Bairisch für Fackel', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Fackel' },
        { id: 'bar-spitzbub', language: 'bar', displayAnswer: 'Spitzbub', clue: 'Bairisch für einen vorlauten, frechen Buben', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'vorlauter Junge' },
        { id: 'bar-ferdl', language: 'bar', displayAnswer: 'Ferdl', clue: 'Bairische Verniedlichung des Pferdes', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Pferdchen' },
        { id: 'bar-knoedl', language: 'bar', displayAnswer: 'Knödl', clue: 'Bairisch für einen Kloß aus Teig', difficulty: 3, allowedProfiles: ['schwer'], region: 'mittelbairisch', standardGerman: 'Kloß' },
        { id: 'bar-seml', language: 'bar', displayAnswer: 'Seml', clue: 'Bairisch für Semmel/Brötchen', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Semmel' },
        { id: 'bar-mocht', language: 'bar', displayAnswer: 'Mocht', clue: 'Bairisch für „macht"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'macht' },
        { id: 'bar-gaht', language: 'bar', displayAnswer: 'Gaht', clue: 'Bairisch für „geht"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'geht' },
        { id: 'bar-doo', language: 'bar', displayAnswer: 'Doo', clue: 'Bairisch für „hin, dorthin"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'hin, dorthin' },
        { id: 'bar-oida', language: 'bar', displayAnswer: 'Oida', clue: 'Bairisch für „Alter"; auch eine Anrede', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Alter' },
        { id: 'bar-hoam', language: 'bar', displayAnswer: 'Hoam', clue: 'Bairisch für Heim, die Heimat', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Heim' },
        { id: 'bar-wuid', language: 'bar', displayAnswer: 'Wuid', clue: 'Bairisch für „wild"', difficulty: 1, allowedProfiles: ['leicht', 'mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'wild' },
        { id: 'bar-fraud', language: 'bar', displayAnswer: 'Fraud', clue: 'Bairisch für „Freude"', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Freude' },
        { id: 'bar-maenna', language: 'bar', displayAnswer: 'Männa', clue: 'Bairisch für Männer', difficulty: 2, allowedProfiles: ['mittel', 'schwer'], region: 'mittelbairisch', standardGerman: 'Männer' }
    ];

    // Erweiterung v1.5: kompakt gepflegte, redaktionell formulierte Einträge.
    // Schema je Zeile: [id-Suffix, natürliche Antwort, eindeutiger Hinweis, Stufe].
    var EXTRA_DE = [
        // Tiere, Pflanzen und Landschaft
        ['adler', 'Adler', 'Großer Greifvogel mit kräftigem Schnabel', 1],
        ['amsel', 'Amsel', 'Schwarzer Singvogel mit gelbem Schnabel', 1],
        ['dachs', 'Dachs', 'Schwarz-weiß gezeichnetes Tier im Erdbau', 2],
        ['fuchs', 'Fuchs', 'Rotbraunes Raubtier mit buschigem Schwanz', 1],
        ['hase', 'Hase', 'Feldtier mit langen Ohren', 1],
        ['igel', 'Igel', 'Kleines Säugetier mit Stachelkleid', 1],
        ['otter', 'Otter', 'Schwimmendes Raubtier an Flüssen', 2],
        ['luchs', 'Luchs', 'Wildkatze mit Pinselohren', 2],
        ['reh', 'Reh', 'Zierliches heimisches Waldtier', 1],
        ['hirsch', 'Hirsch', 'Waldtier, dessen Männchen ein Geweih trägt', 1],
        ['wal', 'Wal', 'Sehr großes Meeressäugetier', 1],
        ['delfin', 'Delfin', 'Intelligentes Meeressäugetier mit Schnauze', 1],
        ['robbe', 'Robbe', 'Flossenfüßer an Küsten und im Meer', 2],
        ['eule', 'Eule', 'Nachtaktiver Vogel mit großen Augen', 1],
        ['falke', 'Falke', 'Schneller Greifvogel im Sturzflug', 2],
        ['rabe', 'Rabe', 'Großer schwarzer Vogel aus der Familie der Krähen', 1],
        ['storch', 'Storch', 'Langbeiniger Zugvogel mit rotem Schnabel', 1],
        ['schwan', 'Schwan', 'Großer Wasservogel mit langem Hals', 1],
        ['ente', 'Ente', 'Wasservogel mit breitem Schnabel', 1],
        ['huhn', 'Huhn', 'Hausvogel, der Eier legt', 1],
        ['ziege', 'Ziege', 'Kletterfreudiges Haustier mit Hörnern', 1],
        ['schaf', 'Schaf', 'Wolllieferndes Weidetier', 1],
        ['loewe', 'Löwe', 'Großkatze mit Mähne', 1],
        ['tiger', 'Tiger', 'Gestreifte asiatische Großkatze', 1],
        ['zebra', 'Zebra', 'Afrikanisches Huftier mit Streifen', 1],
        ['giraffe', 'Giraffe', 'Afrikanisches Tier mit sehr langem Hals', 1],
        ['affe', 'Affe', 'Primat, der geschickt klettern kann', 1],
        ['baer', 'Bär', 'Großes Raubtier mit dichtem Fell', 1],
        ['wolf', 'Wolf', 'In Rudeln lebender Verwandter des Hundes', 1],
        ['kaefer', 'Käfer', 'Insekt mit harten Flügeldecken', 2],
        ['libelle', 'Libelle', 'Schillerndes Fluginsekt am Wasser', 2],
        ['ameise', 'Ameise', 'Staatenbildendes kleines Insekt', 1],
        ['spinne', 'Spinne', 'Achtbeiniges Tier, das oft Netze baut', 1],
        ['krabbe', 'Krabbe', 'Seitwärts laufendes Krebstier', 1],
        ['koralle', 'Koralle', 'Koloniebildendes Nesseltier im Riff', 2],
        ['alge', 'Alge', 'Einfaches Gewächs im Wasser', 2],
        ['moos', 'Moos', 'Weiches grünes Polster auf feuchtem Boden', 1],
        ['farn', 'Farn', 'Sporenpflanze mit gefiederten Wedeln', 2],
        ['eiche', 'Eiche', 'Laubbaum mit gelappten Blättern und becherförmigen Nussfrüchten', 1],
        ['buche', 'Buche', 'Laubbaum mit glatter grauer Rinde', 2],
        ['ahorn', 'Ahorn', 'Baum mit handförmigen Blättern', 2],
        ['tanne', 'Tanne', 'Nadelbaum mit aufrechten Zapfen', 1],
        ['fichte', 'Fichte', 'Nadelbaum mit hängenden Zapfen', 2],
        ['kiefer', 'Kiefer', 'Nadelbaum mit langen Nadeln', 2],
        ['birke', 'Birke', 'Baum mit auffällig weißer Rinde', 1],
        ['linde', 'Linde', 'Laubbaum mit herzförmigen Blättern', 2],
        ['klee', 'Klee', 'Wiesenpflanze, vierblättrig ein Glückssymbol', 1],
        ['tulpe', 'Tulpe', 'Frühlingsblume aus einer Zwiebel', 1],
        ['lilie', 'Lilie', 'Blume mit trichterförmiger Blüte', 2],
        ['orchidee', 'Orchidee', 'Blütenpflanze mit vielen exotischen Arten', 2],
        ['krokus', 'Krokus', 'Früher Frühlingsblüher', 2],
        ['distel', 'Distel', 'Stachelige Pflanze mit violetten Blüten', 2],
        ['kueste', 'Küste', 'Grenzlinie zwischen Land und Meer', 1],
        ['tal', 'Tal', 'Landschaftliche Senke zwischen Bergen', 1],
        ['ebene', 'Ebene', 'Weitgehend flache Landschaft', 1],
        ['wueste', 'Wüste', 'Sehr trockene, niederschlagsarme Landschaft', 1],
        ['oase', 'Oase', 'Wasserreiche Stelle in einer Wüste', 1],
        ['vulkan', 'Vulkan', 'Berg, aus dem Magma austreten kann', 1],
        ['gletscher', 'Gletscher', 'Langsam fließende Masse aus Eis', 2],
        ['quelle', 'Quelle', 'Ort, an dem Grundwasser zutage tritt', 1],
        ['bach', 'Bach', 'Kleines fließendes Gewässer', 1],
        ['see', 'See', 'Von Land umgebenes größeres Gewässer', 1],
        ['teich', 'Teich', 'Kleines stehendes Binnengewässer', 1],
        ['meer', 'Meer', 'Große zusammenhängende Salzwasserfläche', 1],
        ['bucht', 'Bucht', 'Ins Land reichender Teil eines Gewässers', 2],
        ['klippe', 'Klippe', 'Steil abfallender Felsen an einer Küste', 2],
        ['hoehle', 'Höhle', 'Natürlicher unterirdischer Hohlraum', 1],
        ['duene', 'Düne', 'Vom Wind aufgeschütteter Sandhügel', 2],
        ['riff', 'Riff', 'Fels- oder Korallenbank dicht unter Wasser', 2],
        ['steppe', 'Steppe', 'Baumarme Graslandschaft', 2],
        ['delta', 'Delta', 'Verzweigte Flussmündung in Dreiecksform', 2],

        // Wissenschaft, Körper und Mathematik
        ['atom', 'Atom', 'Kleinste chemisch nicht weiter teilbare Einheit', 2],
        ['molekuel', 'Molekül', 'Verbund aus mindestens zwei Atomen', 2],
        ['energie', 'Energie', 'Physikalische Fähigkeit, Arbeit zu verrichten', 2],
        ['schwerkraft', 'Schwerkraft', 'Anziehung zwischen Körpern mit Masse', 2],
        ['magnet', 'Magnet', 'Körper mit Nord- und Südpol', 1],
        ['kompass', 'Kompass', 'Instrument zur Bestimmung der Himmelsrichtung', 1],
        ['teleskop', 'Teleskop', 'Fernrohr zur Beobachtung des Himmels', 2],
        ['mikroskop', 'Mikroskop', 'Instrument zur starken Vergrößerung kleinster Dinge', 2],
        ['planet', 'Planet', 'Himmelskörper auf einer Bahn um einen Stern', 1],
        ['galaxie', 'Galaxie', 'Riesiges System aus Sternen, Gas und Staub', 2],
        ['umlaufbahn', 'Umlaufbahn', 'Geschlossener Weg eines Himmelskörpers', 2],
        ['meteor', 'Meteor', 'Leuchterscheinung eines Körpers in der Atmosphäre', 2],
        ['krater', 'Krater', 'Trichterförmige Vertiefung auf einem Himmelskörper', 2],
        ['prisma', 'Prisma', 'Glaskörper, der Licht in Farben zerlegt', 2],
        ['laser', 'Laser', 'Gebündelter, kohärenter Lichtstrahl', 2],
        ['linse', 'Linse', 'Gewölbter optischer Körper zur Lichtbrechung', 2],
        ['formel', 'Formel', 'Kompakte Darstellung eines mathematischen Zusammenhangs', 1],
        ['algebra', 'Algebra', 'Teilgebiet der Mathematik mit Variablen', 2],
        ['geometrie', 'Geometrie', 'Lehre von Formen, Längen und Winkeln', 2],
        ['winkel', 'Winkel', 'Figur aus zwei Strahlen mit gemeinsamem Anfang', 1],
        ['radius', 'Radius', 'Abstand vom Kreismittelpunkt zum Rand', 1],
        ['flaeche', 'Fläche', 'Zweidimensionale Ausdehnung', 1],
        ['volumen', 'Volumen', 'Rauminhalt eines Körpers', 1],
        ['ziffer', 'Ziffer', 'Ein einzelnes Zeichen zur Darstellung einer Zahl', 1],
        ['bruch', 'Bruch', 'Zahl aus Zähler und Nenner', 1],
        ['summe', 'Summe', 'Ergebnis einer Addition', 1],
        ['produkt', 'Produkt', 'Ergebnis einer Multiplikation', 1],
        ['quotient', 'Quotient', 'Ergebnis einer Division', 2],
        ['faktor', 'Faktor', 'Zahl in einer Multiplikation', 1],
        ['primzahl', 'Primzahl', 'Nur durch eins und sich selbst teilbare Zahl', 2],
        ['elektron', 'Elektron', 'Negativ geladenes Elementarteilchen', 2],
        ['proton', 'Proton', 'Positiv geladenes Teilchen im Atomkern', 2],
        ['neutron', 'Neutron', 'Elektrisch neutrales Teilchen im Atomkern', 2],
        ['zelle', 'Zelle', 'Kleinste selbstständig lebensfähige biologische Einheit', 2],
        ['gen', 'Gen', 'Abschnitt der Erbinformation', 2],
        ['dns', 'DNS', 'Molekül, das die Erbinformation trägt', 3],
        ['bakterium', 'Bakterium', 'Einzelliger Mikroorganismus ohne Zellkern', 2],
        ['virus', 'Virus', 'Krankheitserreger, der Wirtszellen benötigt', 2],
        ['impfung', 'Impfung', 'Vorbeugende Gabe zum Aufbau eines Immunschutzes', 1],
        ['organ', 'Organ', 'Körperteil mit einer bestimmten Aufgabe', 1],
        ['lunge', 'Lunge', 'Organ für den Gasaustausch beim Atmen', 1],
        ['leber', 'Leber', 'Großes Organ für Stoffwechsel und Entgiftung', 2],
        ['niere', 'Niere', 'Paariges Organ zur Filterung des Blutes', 2],
        ['gehirn', 'Gehirn', 'Zentrales Organ des Nervensystems', 1],
        ['muskel', 'Muskel', 'Zusammenziehbares Gewebe für Bewegung', 1],
        ['knochen', 'Knochen', 'Hartes Stützgewebe des Skeletts', 1],
        ['haut', 'Haut', 'Äußere Schutzhülle des Körpers', 1],

        // Sprache, Kunst und Medien
        ['musik', 'Musik', 'Kunst aus geordneten Tönen und Klängen', 1],
        ['lied', 'Lied', 'Gesungenes Musikstück', 1],
        ['oper', 'Oper', 'Musiktheater mit überwiegend gesungenem Text', 2],
        ['theater', 'Theater', 'Bühnenkunst mit dargestellten Rollen', 1],
        ['buehne', 'Bühne', 'Erhöhter Spielort für Aufführungen', 1],
        ['film', 'Film', 'Folge bewegter Bilder mit Handlung', 1],
        ['kino', 'Kino', 'Ort, an dem Filme vorgeführt werden', 1],
        ['kamera', 'Kamera', 'Gerät zum Aufnehmen von Bildern', 1],
        ['foto', 'Foto', 'Mit einer Kamera aufgenommenes Bild', 1],
        ['pinsel', 'Pinsel', 'Werkzeug mit Borsten zum Malen', 1],
        ['farbe', 'Farbe', 'Wahrnehmung verschiedener Lichtwellenlängen', 1],
        ['leinwand', 'Leinwand', 'Gewebe als Malgrund oder Projektionsfläche', 2],
        ['skulptur', 'Skulptur', 'Dreidimensionales Werk der bildenden Kunst', 2],
        ['museum', 'Museum', 'Haus zum Sammeln und Ausstellen von Kulturgut', 1],
        ['galerie', 'Galerie', 'Ausstellungsraum für Kunstwerke', 2],
        ['roman', 'Roman', 'Längere erzählende Prosadichtung', 1],
        ['gedicht', 'Gedicht', 'Literarischer Text in Versen', 1],
        ['autor', 'Autor', 'Verfasser eines Textes', 1],
        ['leser', 'Leser', 'Person, die einen Text liest', 1],
        ['verlag', 'Verlag', 'Unternehmen, das Bücher veröffentlicht', 2],
        ['kapitel', 'Kapitel', 'Größerer Abschnitt eines Buches', 1],
        ['absatz', 'Absatz', 'Durch Zeilenumbruch gegliederter Textteil', 2],
        ['satz', 'Satz', 'Grammatische Einheit aus zusammengehörigen Wörtern', 1],
        ['wort', 'Wort', 'Selbstständige sprachliche Bedeutungseinheit', 1],
        ['silbe', 'Silbe', 'Sprecheinheit mit einem Lautgipfel', 2],
        ['reim', 'Reim', 'Gleichklang am Ende von Versen', 1],
        ['vers', 'Vers', 'Einzelne Zeile eines Gedichts', 2],
        ['drama', 'Drama', 'Für die Bühne geschriebener Handlungstext', 2],
        ['komoedie', 'Komödie', 'Dramatische Gattung mit heiterem Ausgang', 2],
        ['tragoedie', 'Tragödie', 'Drama mit schwerem oder tödlichem Konflikt', 2],
        ['maerchen', 'Märchen', 'Erzählung mit wundersamen Ereignissen', 1],
        ['sage', 'Sage', 'Überlieferte Erzählung mit historischem Kern', 2],
        ['legende', 'Legende', 'Überlieferte Geschichte um eine besondere Person', 2],
        ['raetsel', 'Rätsel', 'Aufgabe, deren Lösung durch Nachdenken gefunden wird', 1],
        ['loesung', 'Lösung', 'Gesuchtes Ergebnis einer Aufgabe', 1],

        // Berufe, Orte und Alltagsgegenstände
        ['arzt', 'Arzt', 'Person, die Krankheiten untersucht und behandelt', 1],
        ['lehrer', 'Lehrer', 'Person, die Wissen und Fähigkeiten vermittelt', 1],
        ['baecker', 'Bäcker', 'Handwerker, der Brot und Gebäck herstellt', 1],
        ['koch', 'Koch', 'Person, die beruflich Speisen zubereitet', 1],
        ['bauer', 'Bauer', 'Person, die einen landwirtschaftlichen Betrieb führt', 1],
        ['gaertner', 'Gärtner', 'Fachkraft für Pflanzen und Grünanlagen', 1],
        ['fahrer', 'Fahrer', 'Person am Steuer eines Fahrzeugs', 1],
        ['pilot', 'Pilot', 'Person, die ein Flugzeug steuert', 1],
        ['kapitaen', 'Kapitän', 'Verantwortlicher Führer eines Schiffes', 2],
        ['richter', 'Richter', 'Person, die vor Gericht Urteile spricht', 2],
        ['anwalt', 'Anwalt', 'Juristischer Vertreter einer Partei', 2],
        ['maler', 'Maler', 'Beruf für Anstriche oder bildende Kunst', 1],
        ['maurer', 'Maurer', 'Bauhandwerker für Wände aus Stein', 2],
        ['tischler', 'Tischler', 'Handwerker für Möbel und Bauteile aus Holz', 2],
        ['schmied', 'Schmied', 'Handwerker, der Metall durch Schlagen formt', 2],
        ['forscher', 'Forscher', 'Person, die systematisch neue Erkenntnisse sucht', 2],
        ['musiker', 'Musiker', 'Person, die ein Instrument spielt oder singt', 1],
        ['saenger', 'Sänger', 'Person, die mit der Stimme Musik macht', 1],
        ['taenzer', 'Tänzer', 'Person, die sich rhythmisch zur Musik bewegt', 1],
        ['beruf', 'Beruf', 'Auf Dauer ausgeübte bezahlte Tätigkeit', 1],
        ['schule', 'Schule', 'Einrichtung zum Lernen und Unterrichten', 1],
        ['klasse', 'Klasse', 'Gemeinsam unterrichtete Gruppe von Schülern', 1],
        ['heft', 'Heft', 'Zusammengefügte Blätter zum Schreiben', 1],
        ['stift', 'Stift', 'Handliches Werkzeug zum Schreiben oder Zeichnen', 1],
        ['kreide', 'Kreide', 'Weicher Kalkstein zum Schreiben an Tafeln', 1],
        ['lineal', 'Lineal', 'Gerade Messhilfe zum Zeichnen von Linien', 1],
        ['schere', 'Schere', 'Werkzeug mit zwei gegeneinander bewegten Klingen', 1],
        ['kleber', 'Kleber', 'Stoff zum dauerhaften Verbinden von Flächen', 1],
        ['tasche', 'Tasche', 'Behältnis mit Griff oder Riemen', 1],
        ['koffer', 'Koffer', 'Stabiles Reisegepäck mit Deckel', 1],
        ['schluessel', 'Schlüssel', 'Gegenstand zum Öffnen eines Schlosses', 1],
        ['schloss', 'Schloss', 'Vorrichtung zum Sichern einer Tür', 1],
        ['bruecke', 'Brücke', 'Bauwerk über ein Hindernis', 1],
        ['turm', 'Turm', 'Hohes, schmales Bauwerk', 1],
        ['kirche', 'Kirche', 'Christliches Gotteshaus', 1],
        ['rathaus', 'Rathaus', 'Sitz der Verwaltung einer Gemeinde', 1],
        ['bahnhof', 'Bahnhof', 'Anlage zum Ein- und Aussteigen bei Zügen', 1],
        ['hafen', 'Hafen', 'Geschützter Liegeplatz für Schiffe', 1],
        ['flughafen', 'Flughafen', 'Anlage für Start und Landung von Flugzeugen', 1],
        ['markt', 'Markt', 'Ort des Handels mit Waren', 1],
        ['laden', 'Laden', 'Geschäftsraum für den Verkauf von Waren', 1],
        ['kasse', 'Kasse', 'Stelle zum Bezahlen in einem Geschäft', 1],
        ['muenze', 'Münze', 'Geprägtes Zahlungsmittel aus Metall', 1],
        ['schein', 'Schein', 'Bedrucktes Zahlungsmittel aus Papier oder Kunststoff', 2],
        ['preis', 'Preis', 'Geldbetrag, der für eine Ware verlangt wird', 1],
        ['rabatt', 'Rabatt', 'Nachlass auf einen verlangten Preis', 1],
        ['rechnung', 'Rechnung', 'Aufstellung über eine zu zahlende Leistung', 1],

        // Lebensmittel und Küche
        ['kaese', 'Käse', 'Aus Milch hergestelltes gereiftes Lebensmittel', 1],
        ['butter', 'Butter', 'Streichfett aus Rahm', 1],
        ['honig', 'Honig', 'Süßer Vorrat, den Bienen herstellen', 1],
        ['zucker', 'Zucker', 'Süß schmeckender kristalliner Stoff', 1],
        ['salz', 'Salz', 'Kristallines Würzmittel aus Natriumchlorid', 1],
        ['pfeffer', 'Pfeffer', 'Scharfes Gewürz aus getrockneten Beeren', 1],
        ['mehl', 'Mehl', 'Fein gemahlenes Getreideprodukt', 1],
        ['reis', 'Reis', 'Kleine Körner einer asiatischen Getreidepflanze', 1],
        ['nudel', 'Nudel', 'Geformtes Teigprodukt, das gekocht wird', 1],
        ['suppe', 'Suppe', 'Flüssige oder sämige Speise aus einem Topf', 1],
        ['salat', 'Salat', 'Kalte Speise aus gemischten Zutaten', 1],
        ['orange', 'Orange', 'Runde Zitrusfrucht mit kräftig gefärbter Schale', 1],
        ['zitrone', 'Zitrone', 'Saure gelbe Zitrusfrucht', 1],
        ['banane', 'Banane', 'Längliche gelbe Tropenfrucht', 1],
        ['birne', 'Birne', 'Nach unten bauchige Kernfrucht', 1],
        ['kirsche', 'Kirsche', 'Kleine runde Steinfrucht, meist rot', 1],
        ['pflaume', 'Pflaume', 'Violette oder blaue Steinfrucht', 1],
        ['traube', 'Traube', 'Beere, die in dichten Rispen wächst', 1],
        ['erdbeere', 'Erdbeere', 'Rote Sammelnussfrucht mit grüner Krone', 1],
        ['himbeere', 'Himbeere', 'Weiche rote Sammelsteinfrucht', 1],
        ['kartoffel', 'Kartoffel', 'Stärkehaltige Knolle der Nachtschattengewächse', 1],
        ['karotte', 'Karotte', 'Orangefarbene essbare Wurzel', 1],
        ['zwiebel', 'Zwiebel', 'Scharfe Gemüsepflanze aus übereinanderliegenden Schalen', 1],
        ['gurke', 'Gurke', 'Längliches grünes Gemüse mit hohem Wasseranteil', 1],
        ['tomate', 'Tomate', 'Rote Frucht eines Nachtschattengewächses', 1],
        ['bohne', 'Bohne', 'Hülsenfrucht mit nierenförmigen Samen', 1],
        ['erbse', 'Erbse', 'Kleine runde Hülsenfrucht', 1],
        ['kohl', 'Kohl', 'Gemüsepflanze mit dicht stehenden Blättern', 1],
        ['mais', 'Mais', 'Getreide mit Körnern an einem Kolben', 1],
        ['pizza', 'Pizza', 'Flacher belegter Hefeteig aus dem Ofen', 1],
        ['keks', 'Keks', 'Kleines trockenes Gebäck', 1],
        ['waffel', 'Waffel', 'Gebäck mit typischem Gittermuster', 1],
        ['torte', 'Torte', 'Mehrschichtiges feines Festgebäck', 1],
        ['kaffee', 'Kaffee', 'Heißgetränk aus gerösteten Bohnen', 1],
        ['tee', 'Tee', 'Aufgussgetränk aus Blättern oder Kräutern', 1],
        ['kakao', 'Kakao', 'Getränk oder Pulver aus fermentierten Tropensamen', 1],
        ['saft', 'Saft', 'Aus Früchten oder Gemüse gepresste Flüssigkeit', 1],

        // Begriffe, Richtungen und Sport
        ['freude', 'Freude', 'Gefühl lebhafter Zufriedenheit', 1],
        ['mut', 'Mut', 'Bereitschaft, trotz Gefahr zu handeln', 1],
        ['angst', 'Angst', 'Gefühl bei wahrgenommener Bedrohung', 1],
        ['glueck', 'Glück', 'Günstiger Zufall oder tiefe Zufriedenheit', 1],
        ['ruhe', 'Ruhe', 'Zustand ohne Bewegung oder störenden Lärm', 1],
        ['laerm', 'Lärm', 'Störendes lautes Geräusch', 1],
        ['frieden', 'Frieden', 'Zustand ohne Krieg oder gewaltsamen Konflikt', 1],
        ['streit', 'Streit', 'Heftige Meinungsverschiedenheit', 1],
        ['liebe', 'Liebe', 'Starke Zuneigung zu einem Menschen', 1],
        ['freund', 'Freund', 'Vertraute Person, der man verbunden ist', 1],
        ['familie', 'Familie', 'Gemeinschaft nah verwandter Menschen', 1],
        ['kind', 'Kind', 'Junger Mensch vor dem Erwachsenenalter', 1],
        ['eltern', 'Eltern', 'Mutter und Vater eines Kindes', 1],
        ['bruder', 'Bruder', 'Männliches Geschwisterkind', 1],
        ['schwester', 'Schwester', 'Weibliches Geschwisterkind', 1],
        ['frage', 'Frage', 'Äußerung, die eine Auskunft verlangt', 1],
        ['antwort', 'Antwort', 'Reaktion auf eine gestellte Frage', 1],
        ['anfang', 'Anfang', 'Erster Abschnitt eines Ablaufs', 1],
        ['ende', 'Ende', 'Letzter Abschnitt eines Ablaufs', 1],
        ['mitte', 'Mitte', 'Bereich mit gleichem Abstand zu zwei Rändern', 1],
        ['norden', 'Norden', 'Himmelsrichtung zum geografischen Nordpol', 1],
        ['sueden', 'Süden', 'Himmelsrichtung gegenüber Norden', 1],
        ['osten', 'Osten', 'Himmelsrichtung des Sonnenaufgangs', 1],
        ['westen', 'Westen', 'Himmelsrichtung des Sonnenuntergangs', 1],
        ['ball', 'Ball', 'Runder Spielgegenstand vieler Sportarten', 1],
        ['tor', 'Tor', 'Zielrahmen in vielen Mannschaftssportarten', 1],
        ['team', 'Team', 'Gemeinsam antretende Gruppe', 1],
        ['trainer', 'Trainer', 'Person, die Sportler anleitet', 1],
        ['stadion', 'Stadion', 'Große Anlage für Sportveranstaltungen', 1],
        ['fussball', 'Fußball', 'Mannschaftssport mit Ball und zwei Toren', 1],
        ['tennis', 'Tennis', 'Rückschlagsport mit Schläger und Netz', 1],
        ['hockey', 'Hockey', 'Mannschaftssport mit Schlägern und kleinem Ball', 2],
        ['ski', 'Ski', 'Langes Gleitgerät für Schnee', 1],
        ['segel', 'Segel', 'Tuchfläche, die Wind zum Antrieb nutzt', 1],
        ['ruder', 'Ruder', 'Stange mit Blatt zum Antrieb eines Bootes', 1],
        ['lauf', 'Lauf', 'Fortbewegung mit schnellen Schritten', 1],
        ['sprung', 'Sprung', 'Bewegung, bei der beide Füße den Boden verlassen', 1],
        ['sieg', 'Sieg', 'Erfolgreicher Ausgang eines Wettkampfs', 1]
    ];

    function profilesForDifficulty(level) {
        return level === 1 ? ['leicht', 'mittel', 'schwer'] : level === 2 ? ['mittel', 'schwer'] : ['schwer'];
    }
    EXTRA_DE.forEach(function (item) {
        RAW.push({
            id: 'de-' + item[0], language: 'de', displayAnswer: item[1], clue: item[2],
            difficulty: item[3], allowedProfiles: profilesForDifficulty(item[3])
        });
    });

    var REVIEW = Object.freeze({ status: 'project-reviewed', reviewerRole: 'project-editor', reviewDate: '2026-08-26' });
    var SOURCE = Object.freeze({ kind: 'project-editorial' });

    var entries = RAW.map(function (raw) {
        var entry = {
            id: raw.id,
            language: raw.language,
            displayAnswer: raw.displayAnswer,
            gridAnswer: normalize(raw.displayAnswer),
            clue: raw.clue,
            difficulty: raw.difficulty,
            allowedProfiles: raw.allowedProfiles.slice(),
            reviewed: true,
            review: REVIEW,
            source: SOURCE
        };
        if (raw.language === 'bar') {
            entry.region = raw.region;
            entry.standardGerman = raw.standardGerman;
        }
        return Object.freeze(entry);
    });

    var dataset = Object.freeze({
        schemaVersion: 2,
        datasetVersion: DATASET_VERSION,
        editorialPolicy: Object.freeze({
            clueStyle: 'kurz, grammatisch vollständig, ohne direkte Antwortnennung',
            normalization: 'NFC; Ä/Ö/Ü→AE/OE/UE; ß→SS; Trennzeichen entfallen im Gitter',
            dialectScope: 'Bairisch mit ausgewiesener Region und standarddeutscher Bedeutung'
        }),
        entries: entries
    });

    if (typeof module === 'object' && module.exports) {
        module.exports = dataset;
    } else {
        root.PandakreuzwortData = dataset;
    }
    return dataset;
})(typeof globalThis !== 'undefined' ? globalThis : window, function () { return null; });
